### ISSUE TITLE
Very slow pickle on pandas Data Frame

### ISSUE THREAD

**Issue by kamalbowselvam** [tomerfiliba/rpyc#323] opened 2019-04-10 10:46 UTC
Hello,

I am trying to write a huge pandas data frame to Hdf5 via server. The data frame is sent from the client. 
I figured out that, I should use rpyc.classic.obtain() to unpickle my object before appending it to Hdf5Store. If I don't unpickle, pandas throws an error, as it is netref object. 

For smaller data frame, the unpickle is faster, but when the data frame size is huge, it takes a lot of time to unpickle it and append. Is there a work around for this problem ? 

Or is there some other method that I should use ? I have attached a minimal example below:

##### Environment

- rpyc 4.0.2
- pandas 0.24.2
- python 3.7.3
- Windows

##### Minimal example

Server:

```
import logging
import rpyc

class DummyServer(rpyc.Service):

    def on_connect(self,conn):
        print("Starting Server")
        pass

    def on_disconnect(self,conn):
        pass

    def exposed_write_data(self,dataframe):
        data = pd.HDFStore("Test.h5")
        start = time.time()
        realdata = rpyc.classic.obtain(dataframe)
        end = time.time()
        print(end-start)
        data.append("DATA",realdata)
        print("Writing Data Completed")
        data.close()


if __name__ == "__main__":
    t = ThreadedServer(DummyServer(), port=18860,protocol_config = rpyc.core.protocol.DEFAULT_CONFIG)
    t.start()
```

Client:

```
import rpyc
import pandas as pd
rpyc.core.protocol.DEFAULT_CONFIG['allow_pickle'] = True

conn = rpyc.connect("localhost",18860, config=rpyc.core.protocol.DEFAULT_CONFIG)
server = conn.root

import datetime
import pandas as pd
import numpy as np

N = 10000
M = 10000

todays_date = datetime.datetime.now().date()
index = pd.date_range(todays_date-datetime.timedelta(N), periods=N, freq='D')
columns = [str(x) for x in range(M)]
data = np.array([np.arange(N)]*M).T
df = pd.DataFrame(data, index=index, columns=columns)

server.write_data(df)
```

**Comment by comrumino** [comment] 2019-06-10 04:29
Thanks for reporting this issue. I've confirmed the issue and it turns out that the issue is a duplicate of #329. Closing this issue (I already started documenting under #329 ).

**Closed by comrumino** 2019-06-10 04:29 UTC
