### ISSUE TITLE
using rpyc.utils.zerodeploy, with IPython, getting a TypeError "hash of object needs an argument"

### ISSUE THREAD

**Issue by delandtj** [tomerfiliba/rpyc#293] opened 2018-08-25 11:55 UTC
placeholder for now, will fill in later with more information (repro script etc.)
```
/home/lkcl/src/rpyc/rpyc/core/async_.py in value(self)
     95         self.wait()
     96         if self._is_exc:
---> 97             raise self._obj
     98         else:
     99             return self._obj

TypeError: descriptor '__hash__' of 'object' object needs an argument

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/root/tmp.dMXeoymwGh/rpyc/core/protocol.py", line 329, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/root/tmp.dMXeoymwGh/rpyc/core/protocol.py", line 603, in _handle_callattr
    return self._handle_call(obj, args, kwargs)
  File "/root/tmp.dMXeoymwGh/rpyc/core/protocol.py", line 590, in _handle_call
    return obj(*args, **dict(kwargs))
TypeError: descriptor '__hash__' of 'object' object needs an argument

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/jan/jumpscale/core9/ptest.py in <module>()
----> 1 j.tools.prefab

/usr/lib/python3/dist-packages/IPython/core/displayhook.py in __call__(self, result)
    244             self.start_displayhook()
    245             self.write_output_prompt()
--> 246             format_dict, md_dict = self.compute_format_data(result)
    247             self.update_user_ns(result)
    248             self.fill_exec_result(result)

/usr/lib/python3/dist-packages/IPython/core/displayhook.py in compute_format_data(self, result)
    148 
    149         """
--> 150         return self.shell.display_formatter.format(result)
    151 
    152     # This can be set to True by the write_output_prompt method in a subclass

/usr/lib/python3/dist-packages/IPython/core/formatters.py in format(self, obj, include, exclude)
    150             return {}, {}
    151 
--> 152         format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
    153 
    154         if format_dict or md_dict:

TypeError: 'NoneType' object is not iterable
```

**Comment by delandtj** [comment] 2018-08-25 11:56
this is in IPython embed, on hitting "enter" on an object that's been remote-created: normally, the type of the object would be displayed (standard output from repr would be seen)

**Comment by coldfix** [comment] 2018-08-26 16:04
Thanks, can you share your code? There are long standing problems with `__hash__` I believe and I didn't check too extensively last time I merged a PR about it.

**Comment by coldfix** [comment] 2018-09-05 16:37
Closing this as likely duplicate of #280. Will be fixed in the next version. If the problem persists, please open another issue. Thanks!

**Closed by coldfix** 2018-09-05 16:37 UTC
