### ISSUE TITLE
Cannot access __eq__ method on remote object

### ISSUE THREAD

**Issue by fateflame** [tomerfiliba/rpyc#357] opened 2019-10-30 07:15 UTC
I create an object on server, pass its reference to client and make comparison with `server_ret == some_value` on client, which gives me an `AttributeError: cannot access '__eq__'`.  

**Important: `server_ret` is a self defined object passed by referece**。Base types like `int` works fine.  I find this problem when I update my rpyc from 4.1.1 to 4.1.2 **on server**(where the object actually exists). While with rpyc 4.1.1, all works fine..

Here is the main part of traceback info:
```
    if ret == const.ActionResult.LOGIN_REQUIRED.value:
  File "D:\Program Files\Python\Python35\lib\site-packages\rpyc\core\netref.py", line 191, in __eq__
    return syncreq(self, consts.HANDLE_CMP, other, '__eq__')
  File "D:\Program Files\Python\Python35\lib\site-packages\rpyc\core\netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "D:\Program Files\Python\Python35\lib\site-packages\rpyc\core\protocol.py", line 464, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "D:\Program Files\Python\Python35\lib\site-packages\rpyc\core\async_.py", line 102, in value
    raise self._obj
AttributeError: cannot access '__eq__'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/rpyc/core/protocol.py", line 323, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python3.7/dist-packages/rpyc/core/protocol.py", line 577, in _handle_cmp
    return self._access_attr(type(obj), op, (), "_rpyc_getattr", "allow_getattr", getattr)(obj, other)
  File "/usr/local/lib/python3.7/dist-packages/rpyc/core/protocol.py", line 528, in _access_attr
    name = self._check_attr(obj, name, param)
  File "/usr/local/lib/python3.7/dist-packages/rpyc/core/protocol.py", line 513, in _check_attr
    raise AttributeError("cannot access %r" % (name,))
AttributeError: cannot access '__eq__'
```

**Comment by Evidlo** [comment] 2019-10-30 18:09
Have you tried starting your server with `protocol_config={'allow_all_attrs': True}`?

**Comment by fateflame** [comment] 2019-11-01 06:23
> Have you tried starting your server with `protocol_config={'allow_all_attrs': True}`?

No, I didn't.I supposed these methods are exposed by default as everything works find in rpyc 4.1.1.

In addition,, I can use scripts like dict[key], which indicates methods like __getitem__ are also exposed by default as well in 4.1.1(I didn't try in 4.1.2.)

**Comment by comrumino** [comment] 2019-11-07 01:58
To be of more help, I would need a minimal example to reproduce the issue. Not all objects define `__add__` (it is a safe attribute so `allow_all_attrs` is not the answer here).

**Comment by comrumino** [comment] 2019-11-14 19:33
Closing this issue since the discussion is exhausted, but feel free to reopen this issue as needed.

**Closed by comrumino** 2019-11-14 19:33 UTC
Labels: In Progress
