### ISSUE TITLE
Issues with multithreading and async, getting stuck

### ISSUE THREAD

**Issue by TI-AviBerko** [tomerfiliba/rpyc#223] opened 2017-07-16 11:04 UTC
I'm trying to use async with threads in order to not block my threaded server/service.

There's an exposed function in the server that executes a closure in a thread, that function receives a callback function from the client, which is called when the closure returns.

The client calls the function in several threads, each one with it's own callback function and Event object

This works, but eventually gets stuck from some reason. it works on IronPython though without getting stuck.

See this gist: https://gist.github.com/TI-AviBerko/fc6c09d187c764a1be3e19a5de7864e1

**Comment by TI-AviBerko** [comment] 2017-07-18 13:39
I think the issue is that I didn't turn the callback into an async function.
After doing that, the issue doesn't recreate.

Can anyone confirm?

**Comment by coldfix** [comment] 2017-07-18 13:46
Hi,

which version of rpyc are you running? I couldn't reproduce the issue with current master.

If you were running on a release or older commit: Can you try your original code using current master?

**Comment by TI-AviBerko** [comment] 2017-07-18 13:51
I just cloned master and ran the original code, still getting stuck

**Comment by coldfix** [comment] 2017-07-18 13:56
using cpython 2.7?

(Did you uninstall the other rpyc before re-running the test, just to be sure?)

I assume with "getting stuck" you mean that the program is dead-locked?

After how many iterations does this typically happen?

**Comment by TI-AviBerko** [comment] 2017-07-18 14:04
I copied the rpyc directory from master right into the directory I'm running the scripts from.
rpyc.__version__ is (3.4.2)

Python version is 2.7.13.
It takes about 25 iterations to deadlock, looks like the threads aren't finishing due to event.set() not being called.

**Comment by TI-AviBerko** [comment] 2017-07-18 17:00
I forgot to mention I was running this on win7, and it hangs on 2 different PCs

I also just tried it on Ubuntu 14.04 64-bit as well, gets stuck after around 65 iterations.

**Comment by coldfix** [comment] 2017-07-18 17:52
Hi, I can now sometimes reproduce. I'll see if I can find out more.

**Comment by coldfix** [comment] 2017-07-18 18:25
According to the documentation of `rpyc.async` you should store the async object into a variable before calling it (line 16):

```
asy = rpyc.async(conn.root.test)
ret = asy(cb, i)
```

**Comment by TI-AviBerko** [comment] 2017-07-18 18:40
I tried this at least once when I was debugging the IronPython issue I linked.
Anyway, this seems to solve the dead lock issue, and does look related to reference counting on CPython, as the unfixed version works fine on IronPython that doesn't use reference counting...

It's still weird that it just doesn't execute the callback on the client without any errors

**Comment by coldfix** [comment] 2017-07-18 22:27
> and does look related to reference counting on CPython, as the unfixed version works fine on IronPython that doesn't use reference counting...

It's not related to reference counting per se, but you are much more unlikely to notice this on a system with reference counting, because this destroys unreferened (or weakly referenced) objects immediately. It is far less likely that the GC is triggered at the precise time that is required to make the issue appear.

> It's still weird that it just doesn't execute the callback on the client without any errors

In fact, the function on the server is never executed. This has to do with how rpyc uses a weak reference to hold the `conn.root.test` netref. If you don't store this (or the proxy returned by `rpyc.async`) in a variable, it can be deleted from the local objects on the server side. This will trigger an exception when trying to execute the method. If you turn on logging on the server side before going into listening mode, you will see the exception:

```python
import rpyc.lib
rpyc.lib.setup_logger()
```

```
DEBUG:MYSERVER/8888:Exception caught
Traceback (most recent call last):
  File "/home/thomas/dev/project/rpyc/rpyc/core/protocol.py", line 346, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/thomas/dev/project/rpyc/rpyc/core/protocol.py", line 602, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/home/thomas/dev/project/rpyc/rpyc/lib/colls.py", line 86, in __getitem__
    return self._dict[key][0]
KeyError: 140368761365360
```

Now you may wonder, why you don't see anything of this exception on the client side? That's because you didn't add a callback for the async result. You should generally do this, otherwise you have no way of knowing if the server has thrown an exception (not even if it was thrown in your own function) - making your code inherently prone to deadlocking if anything occurs.

Use this client to see what's going on:

```python
def execute(conn, i):
    event = threading.Event()
    def cb(i):
        event.set()

    def cb2(res):
        try:
            res.value
        except BaseException as e:
            event.set()     # avoid infinite wait
            print(e)        # the world should know

    # NOTE: this should be:
    #   asy = rpyc.async(conn.root.test)
    #   ret = asy(cb, i)
    # OR at least:
    #   fun = conn.root.test
    #   ret = rpyc.async(fun)(cb, i)
    ret = rpyc.async(conn.root.test)(cb, i)

    # IMPORTANT: always add a callback, otherwise exceptions will be ignored
    ret.add_callback(cb2)

    print "waiting", i
    event.wait()
    print "waited"
```

Now, if the callback is the last thing to do for the server, it would be much nicer to directly use `ret.add_callback` and remove the `cb` argument from the `exposed_test` function. Not sure whether this can be applied to your actual code. The minimal example would be transformed as follows:

Client:

```python
def execute(conn, i):
    event = threading.Event()
    def cb(res):
        try:
            res.value
        except BaseException as e:
            print(e)        # the world should know
        finally:
            event.set()     # always execute, to avoid infinite lock 

    asy = rpyc.async(conn.root.test)
    ret = asy(i)
    ret.add_callback(cb)

    print "waiting", i
    event.wait()
    print "WAITED"
```

Also, I wonder, whether using an `Event` is really what you want, but this goes beyond the scope of this issue.

Best, Thomas

**Comment by TI-AviBerko** [comment] 2017-07-19 10:31
Thomas,

First, thank you for the support and explaining the issue thoroughly, hopefully it has something to do with the issue I get in IronPython too.

As for why I'm using the Event object, for my use case I need to call functions from different threads without the Service blocking, I understand I can probably do it by just initiating another connection to the server, since I'm using a threaded server, but I wanted to avoid that.

So the best option I found was to spawn a thread for every call in the server and use async to prevent it from blocking, the final piece being the event object to sync on in order to return the result (in my original code it also catches exceptions).

Regards,
Avi

**Comment by coldfix** [comment] 2017-07-21 09:43
Hi, ok I can't really say whether there is a better solution without looking at the code.

Anyway, since this works now, can I close the issue or was there another question?

**Comment by TI-AviBerko** [comment] 2017-07-23 14:10
You can close the issue.
Thanks.

**Closed** 2017-07-23 15:40 UTC
