### ISSUE TITLE
Traceback with "rpyc.classic.connect()"

### ISSUE THREAD

**Issue by naveenshankar61** [tomerfiliba/rpyc#263] opened 2018-04-06 06:47 UTC
I am using python provided rpyc module for my remote connectivity purposes but my command "import rpyc; conn = rpyc.classic.connect(<Hostname>)" yield the following traceback:

```
[root@SM-4-161 masher]# python
Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpyc
>>> conn = rpyc.classic.connect("10.206.110.155")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/utils/classic.py", line 70, in connect
    return factory.connect(host, port, SlaveService, ipv6 = ipv6, keepalive = keepalive)
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/utils/factory.py", line 93, in connect
    return connect_stream(s, service, config)
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/utils/factory.py", line 54, in connect_stream
    return connect_channel(Channel(stream), service=service, config=config)
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/utils/factory.py", line 43, in connect_channel
    return service._connect(channel, config)
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/core/service.py", line 100, in _connect
    self.on_connect(conn)
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/core/service.py", line 195, in on_connect
    self._install(conn, conn.root)
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/core/service.py", line 199, in _install
    modules = ModuleNamespace(slave.getmodule)
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/core/netref.py", line 157, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/core/netref.py", line 77, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/lib/python2.7/site-packages/rpyc-3.4.4-py2.7.egg/rpyc/core/protocol.py", line 516, in sync_request
    raise obj
KeyError: '<rpyc.core.service.SlaveService object at 0x7fbfe0012090>'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rpyc/core/protocol.py", line 347, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python2.7/site-packages/rpyc/core/protocol.py", line 630, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/usr/lib/python2.7/site-packages/rpyc/core/protocol.py", line 588, in _access_attr
    obj = self._local_objects[oid]
  File "/usr/lib/python2.7/site-packages/rpyc/lib/colls.py", line 86, in __getitem__
    return self._dict[key][0]
KeyError: <rpyc.core.service.SlaveService object at 0x7fbfe0012090>

>>>
```

##### Environment

- rpyc version = 3.4.4
- python version = 2.7
- operating system = CentOS-7.4 with kernel upgraded to 4.13.12

Can anyone please help me rectify this issue?

**Comment by madhukeshava** [comment] 2018-04-06 06:52
I am also facing same issue few of setups and can you please share any thoughts

**Comment by coldfix** [comment] 2018-04-09 21:43
Hi, sorry for the delay.

I can't reproduce your issue locally. Can you check whether this only happens if you run the server on a remote host (possibly high latency?) or also on localhost?

**Comment by madhukeshava** [comment] 2018-04-10 03:01
What is high latency? Is thier any parameter to set this?

**Comment by naveenshankar61** [comment] 2018-04-10 04:36
This issue is only seen when we try to connect to a remote server. 
"rpyc.classic.connect()' on 'localhost' works fine.

**Comment by naveenshankar61** [comment] 2018-04-10 10:01
I have confirmed that both my client and server are installed with 3.4.4 versioned rpyc modules.
I have installed through pip only.

**Comment by coldfix** [comment] 2018-04-10 11:54
Does this happen reliably (i.e. how often in %)? What is the ping to the server approximately? 

Can you show the output of `pip freeze`?

**Comment by madhukeshava** [comment] 2018-04-10 15:19
this will happen 100%...we never succeed till now

**Comment by madhukeshava** [comment] 2018-04-11 07:11
please find pip freeze output

**Comment by coldfix** [comment] 2018-04-11 11:32
If you attached the output to your email, I believe github swallowed the attachment. Please include it inline using [code fences](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by madhukeshava** [comment] 2018-04-11 11:37
ok..can you please share your gmail id

**Comment by coldfix** [comment] 2018-04-11 11:40
Just post it here..

**Comment by naveenshankar61** [comment] 2018-04-12 06:47
[pipfreeze_output.zip](https://github.com/tomerfiliba/rpyc/files/1901639/pipfreeze_output.zip)

**Comment by coldfix** [comment] 2018-05-11 18:48
Unfortunately, I still can't reproduce the issue. Feel free to investigate further and update with new information or submit patches.

**Comment by bor8** [comment] 2018-06-11 23:11
I have the same problem with 4.0.0. With 3.4.4 it works. However, the thread creator also has 3.4.4 according to the ZIP file.

**Comment by bor8** [comment] 2018-06-11 23:15
There may be a problem with the upgrade process from rpyc via pip. It's just a guess. I'll keep an eye on it.

**Comment by coldfix** [comment] 2018-06-12 10:50
> I have the same problem with 4.0.0. With 3.4.4 it works.

Maybe it's not the exact same issue then. Can you provide a stack trace?

Can anyone by any chance debug the issue (`rpyc.setup_logger()` and/or `pdb.set_trace`) on their machine? This would be great since I seem unable to reproduce the issue.

> However, the thread creator also has 3.4.4 according to the ZIP file.

I'm not sure what you wanted to say.

**Comment by bor8** [comment] 2018-06-12 14:43
Hello coldfix, with "thread creator" I meant the TC or the OP :)

```
# 3.4.4
python3 /usr/local/bin/rpyc_classic.py --ipv6

INFO:SLAVE/18812:server started on [::]:18812
```

versus

```
# 4.0.0
python3 /usr/local/bin/rpyc_classic.py --ipv6

Traceback (most recent call last):
  File "/usr/local/bin/rpyc_classic.py", line 125, in <module>
    ClassicServer.run()
  File "/usr/local/lib/python3.5/dist-packages/plumbum/cli/application.py", line 500, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/bin/rpyc_classic.py", line 85, in main
    self._serve_mode(ThreadedServer)
  File "/usr/local/bin/rpyc_classic.py", line 96, in _serve_mode
    registrar = self.registrar, auto_register = self.auto_register)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/utils/server.py", line 89, in __init__
    self.listener.bind((hostname, port))
socket.gaierror: [Errno -9] Address family for hostname not supported
```

Maybe here: https://github.com/tomerfiliba/rpyc/compare/3.4.4...master#diff-354f30a63fb0907d4ad57269548329e3L17 ?

**Comment by anavgire** [comment] 2018-06-12 23:58
I was able to reproduce the issue.
Install rpyc=3.4.4 on server and rpyc=4.0.1 on the client, and try connecting.

**Comment by coldfix** [comment] 2018-06-13 00:57
Hi @anavgire, Thanks a lot! With this I was able to reproduce the issue as well.

Communication between different versions of rpyc is not supported, so I will close the issue once the OPs confirm that they were using different versions of rpyc.

@naveenshankar61 @madhukeshava Did you make sure to use exactly the same version of rpyc (and not the master branch on one machine, a fixed version on the other)?

**Comment by coldfix** [comment] 2018-06-13 13:37
Hi, I have verified that this happens if one peer is on 4c8f00429af08cf60d67368115976a43b556efff or later, and one peer is on an earlier commit/version, and it is clear that this commit introduces a backward incompatibility in the protocol. It seems likely to me that the OPs made a mistake when confirming my Apr 10 question about server/client being the same version.

Communication between different rpyc versions is not supported (if they differ by more than the micro/patch number) and can't be addressed in general, so I'm closing this.

Please reopen a new issue if you continue to have problems on the same rpyc version.

**Closed by coldfix** 2018-06-13 13:37 UTC

**Comment by naveenshankar61** [comment] 2018-06-26 08:38
Sorry for the delayed response. 

I used Python 3.4.4 on both my server and client. 
However, with some help from my colleague (@madhukeshava), this issue is somewhat resolved where we had to just start the nfs service in both sides. Once started, rpyc is able to connect.
