### ISSUE TITLE
Jython server uses all available memory

### ISSUE THREAD

**Issue by conradek** [tomerfiliba/rpyc#229] opened 2017-09-01 21:14 UTC
Hi Thomas,

I am running into issues when using jython and rpyc.  It seems like when a rpyc server under jython and is running for 15+ minutes, it runs out of memory and crashes.  When running the same server under python, the issue does not occur.

To duplicate:

- run the server: jython rpyc_server.py
- run the client: python rpyc_client.py

Here is the output from the server when the issue occurs:

Exception in thread "MainThread" java.lang.OutOfMemoryError: Java heap space
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space

Just before the crash, the java process memory usage is ~545MB, CPU load is at ~30%.  At the start of the test it is ~64MB and 1% respectively.

I am running python 2.7.13, jython 2.7.1 and rpyc 3.4.3 on a Windows 10 PC.

-Conrad
[rpyc_tests.zip](https://github.com/tomerfiliba/rpyc/files/1271537/rpyc_tests.zip)

**Comment by coldfix** [comment] 2017-09-02 09:16
Hi Conrad,

thanks for the report.

I'll check whether I can reproduce the issue. Your example seem simple enough. (btw, its preferable if you post files directly so there is no need to download and unpack the zip file)

**Comment by conradek** [comment] 2017-09-02 19:07
Hi Thomas,

Thank you for looking into this.

Initially I did try and drag-n-drop the .py files but an error occurred (see attached screenshot).

-Conrad
![file_type](https://user-images.githubusercontent.com/1447281/29998107-3a3d9ff2-8fd7-11e7-88ba-eefa17faa8b4.png)

**Comment by coldfix** [comment] 2017-09-04 09:20
Hi, I didn't check on windows so far, but could reproduce a similar issue on linux: java process RAM increases up to about 600MB and then requests dramatically slow down (more than 1-2s per request).

So far can't track down the problem.

For reference, I used a bit simplified version of your example.

`server.py`:

```python
import logging
import itertools

import rpyc
from rpyc.utils.server import OneShotServer

ping_counter = itertools.count()

class PingService(rpyc.Service):

    def exposed_ping(self):
        count = next(ping_counter)
        print("ping received: {}".format(count))
        return count

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    s = OneShotServer(PingService, port=18861)
    s.start()
```

`client.py`:

```python
import time
import rpyc

c = rpyc.connect("localhost", 18861)

while True:
    start = time.time()
    count = c.root.ping()
    delta = time.time() - start
    print("ping #{} took: {}s".format(count, delta))
```

**Comment by comrumino** [comment] 2019-05-21 05:08
The [Jython Book](https://www.jython.org/jythonbook/en/1.0/DefiningFunctionsandUsingBuilt-Ins.html) suggests that garbage collection will not occur until there are no more references. Even with forced GC, there is still a small resource leak since the thread for the channel remains alive. Closing the connection regularly will allow Jython to do garbage collection as seen below.
![2019-05-20-233515_720x241_scrot](https://user-images.githubusercontent.com/12876622/58068694-f425cd00-7b57-11e9-9209-629e38050b3c.png)
Closing this issue for now considering the resource leak intensity varies between Jython 2.7.0 and 2.7.1 and does not exist for PyPy or tracemalloc.

**Closed by comrumino** 2019-05-21 05:08 UTC
