### ISSUE TITLE
Getting timeout for long running commands on server

### ISSUE THREAD

**Issue by Arti3DPlayer** [tomerfiliba/rpyc#320] opened 2019-03-05 08:45 UTC
I'm running classic rpyc server. And when I connect to server and perform long running command:

```
rconn = rpyc.classic.connect(host='ip', port='18812')

rsubprocess = rconn.modules.subprocess
rsubprocess.check_output(['my command'], shell=True).decode()
```

I got:

`raise AsyncResultTimeout("result expired") TimeoutError: result expired`

I tried to set:

`rconn._config['timeout'] = 240`
and
`rconn.ASYNC_REQUEST_TIMEOUT = 240`

##### Environment

- rpyc==4.0.2
- python 3.6.2
- osx client -  windows server

**Comment by comrumino** [comment] 2019-05-21 20:02
Configurations are stored within the connection and can be modified like so.
`rconn._config['sync_request_timeout'] = 240`
Since setting configuration values is a usability issue and the issue is already addressed with Services, this won't be fixed.

**Closed by comrumino** 2019-05-21 20:02 UTC
