### ISSUE TITLE
unable to call exposed_ method on a remote server with floating ip.

### ISSUE THREAD

**Issue by raiesmh08** [tomerfiliba/rpyc#321] opened 2019-03-14 17:13 UTC
Describe the issue briefly here, including:

- expected result versus actual result
- involved/problematic methods, e.g. `__call__`
- steps to reproduce
- for bugs, please attach a

```
stack trace / error log
```

##### Environment

- rpyc version
- python version
- operating system

##### Minimal example

Remote Server:

```python
import rpyc
from rpyc.utils.server import OneShotServer
rpyc.lib.setup_logger()

class ListService(rpyc.Service):
    def exposed_concat(self, lst):
        return lst + ['world']

server = OneShotServer(ListService, port=12345)
server.start()
```

Client:

```python
import rpyc
c = rpyc.connect(<remote_server Floating IP>, 12345)
print(c.root.concat(['hello']))
```

All methodology is correct, only I am trying to call exposed_ method, error is something like - 

```
> /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py(133)__getattribute__()
-> def __getattribute__(self, name):
(Pdb) n
> /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py(134)__getattribute__()
-> if name in _local_netref_attrs:
(Pdb) 
> /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py(148)__getattribute__()
-> elif name == "__hash__":
(Pdb) n
> /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py(150)__getattribute__()
-> elif name == "__call__":                          # IronPython issue #10
(Pdb) 
> /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py(152)__getattribute__()
-> elif name == "__array__":
(Pdb) 
> /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py(155)__getattribute__()
-> return syncreq(self, consts.HANDLE_GETATTR, name)
(Pdb) 
TimeoutError: TimeoutE...xpired',)
```

**Comment by comrumino** [comment] 2019-07-15 02:51
That error is when your response takes too long---the break is left open too long. Try increasing `sync_request_timeout` or setting it to `None`. It is possible that with when a fail over occurs or the floating IP moves to another instance that the response is dropped (seems more likely that the peer would close the connection). `socket.timeout: timed out` would occur if it the connection is never established. Without more exact steps to reproduce (i.e. which hosting provider or network setup is used), I'm closing the issue the belief the obvious issue of response time being the case.

Reopen if the issue is still blocking.

**Closed by comrumino** 2019-07-15 02:51 UTC
